<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/

$config['project_name'] = 'DEMO CI';
$config['sitename'] = 'DEMO CI';

$uriSegments = explode('index.php',$_SERVER['PHP_SELF']);

$config['base_url'] = 'http://'.$_SERVER['HTTP_HOST'].$uriSegments[0];
$config['date_time_zone']='EST';
$config['amount_sign']='$';

$config['amount_sign']='$';

$config['twitter_profile'] = 'https://twitter.com/junctionstudio';
$config['instagram_profile'] = 'https://www.instagram.com/junctionstudio/';

$config['address1'] = '151 East Road';
$config['address2'] = 'Seaford VIC 3198';
$config['contact_number'] = '(03) 8765 4329';
$config['contact_email'] = 'connect@junctionstudio.com.au';

if(($_SERVER['HTTP_HOST']==('junctionstudio.com.au')) || $_SERVER['HTTP_HOST']==('www.junctionstudio.com.au'))
{ 
    $config['admin_email'] = 'connect@junctionstudio.com.au';
}
else
{
    //$config['admin_email'] = 'hardik.devariya@tops-int.com';
    $config['admin_email'] = 'kaushik.valiya@tops-int.com';
}

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']	= 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-:`@-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']		= TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']	= 'c';
$config['function_trigger']		= 'm';
$config['directory_trigger']	= 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/

$config['log_date_format'] = 'Y-m-d H:i:s';

$config['common_date_format'] = 'd/m/Y';
$config['common_date_format_javascript'] = 'dd/mm/yy';
$config['common_datetime_format'] = 'd/m/Y h:i A';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'Junction Studio';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'		= the name you want for the cookie
| 'sess_expiration'			= the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'	= Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'		= Whether to encrypt the cookie
| 'sess_use_database'		= Whether to save the session data to a database
| 'sess_table_name'			= The name of the session database table
| 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
| 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']     = 'ci_session';
$config['sess_expiration']	= 7200;
$config['sess_expire_on_close']	= FALSE;
$config['sess_encrypt_cookie']	= FALSE;
$config['sess_use_database']	= FALSE;
$config['sess_table_name']	= 'ci_sessions';
$config['sess_match_ip']	= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 300;
/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']	= "";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;
/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';
/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;
/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';

//view type
$config['front_view']= 'front';
$config['admin_view']= 'admin';

//Defining custom paths
$config['css_path']= $config['base_url']."css/";
$config['bphf_path']= $config['base_url']."bphf/";
$config['bphf_path_doc']= $_SERVER['DOCUMENT_ROOT'].$uriSegments[0]."/bphf/";
$config['front_css_path']= $config['base_url']."css/front/";
$config['admin_css_path']= $config['base_url']."css/admin/";

$config['js_path']= $config['base_url']."js/";
$config['front_js_path']= $config['base_url']."js/front/";
$config['admin_js_path']= $config['base_url']."js/admin/";

$config['admin_base_url'] = $config['base_url'].$config['index_page'].'admin/';
$config['front_base_url'] = $config['base_url'].$config['index_page'].'front/';

$config['ck_editor_path']= $config['base_url']."ckeditor/";

$config['base_path'] = $_SERVER['DOCUMENT_ROOT'];
$config['base_path'] .= preg_replace('@/+$@','',dirname($_SERVER['SCRIPT_NAME'])).'';

$config['image_path']= $config['base_url']."images/";
$config['front_image_path']= $config['base_url']."images/front/";
$config['image_file_path']= $_SERVER['DOCUMENT_ROOT'].'/'.$config['project_name']."/images/";
$config['upload_image_file_path']= $_SERVER['DOCUMENT_ROOT'].$uriSegments[0]."uploads/";
$config['upload_img_path']= $config['base_url']."uploads/";



/* ---------- Agency  photos ------------------ */
$config['agency_photos_big_path']		= $config['base_path']."/uploads/agency/big/";
$config['agency_photos_small_path']		= $config['base_path']."/uploads/agency/small/";

$config['agency_photos_big_url']		= $config['base_url']."uploads/agency/big/";
$config['agency_photos_small_url']		= $config['base_url']."uploads/agency/small/";

/* --------- End Agency ---------------*/

$config['project_img_big_path']			= $config['base_path']."/uploads/project/big/";
$config['project_img_small_path']               = $config['base_path']."/uploads/project/small/";
$config['project_big_img_url']			= $config['base_url']."uploads/project/big/";
$config['project_small_img_url']                = $config['base_url']."uploads/project/small/";

$config['partners_img_big_path']		= $config['base_path']."/uploads/partners/big/";
$config['partners_img_small_path']              = $config['base_path']."/uploads/partners/small/";
$config['partners_big_img_url']			= $config['base_url']."uploads/partners/big/";
$config['partners_small_img_url']               = $config['base_url']."uploads/partners/small/";

$config['about_fields_img_big_path']		= $config['base_path']."/uploads/about_fields/big/";
$config['about_fields_img_small_path']          = $config['base_path']."/uploads/about_fields/small/";
$config['about_fields_big_img_url']		= $config['base_url']."uploads/about_fields/big/";
$config['about_fields_small_img_url']		= $config['base_url']."uploads/about_fields/small/";

$config['project_fields_img_big_path']		= $config['base_path']."/uploads/project_fields/big/";
$config['project_fields_img_small_path']	= $config['base_path']."/uploads/project_fields/small/";
$config['project_fields_big_img_url']		= $config['base_url']."uploads/project_fields/big/";
$config['project_fields_small_img_url']		= $config['base_url']."uploads/project_fields/small/";


 //---- Event Module Event logo and Add more field URL 

$config['event_img_big_path']			= $config['base_path']."/uploads/event/big/";
$config['event_img_small_path']                 = $config['base_path']."/uploads/event/small/";
$config['event_big_img_url']			= $config['base_url']."uploads/event/big/";
$config['event_small_img_url']                  = $config['base_url']."uploads/event/small/";

$config['event_fields_img_big_path']		= $config['base_path']."/uploads/event_fields/big/";
$config['event_fields_img_small_path']	        = $config['base_path']."/uploads/event_fields/small/";
$config['event_fields_big_img_url']		= $config['base_url']."uploads/event_fields/big/";
$config['event_fields_small_img_url']		= $config['base_url']."uploads/event_fields/small/";
//------ End Event URL

$config['slider_img_big_path']		        = $config['base_path']."/uploads/slider/big/";
$config['slider_img_small_path']                = $config['base_path']."/uploads/slider/small/";
$config['slider_big_img_url']		        = $config['base_url']."uploads/slider/big/";
$config['slider_small_img_url']		        = $config['base_url']."uploads/slider/small/";

$config['event_logo_img_big_path']		= $config['base_path']."/uploads/event_logo/big/";
$config['event_logo_img_small_path']            = $config['base_path']."/uploads/event_logo/small/";
$config['event_logo_big_img_url']		= $config['base_url']."uploads/event_logo/big/";
$config['event_logo_small_img_url']             = $config['base_url']."uploads/event_logo/small/";

$config['image_site_logo']                      = $config['base_path']."/images/";
$config['image_site_logo_url']                  = $config['base_url']."images/";

//-- USER PROFILE PIC
$config['user_img_big_path']			= $config['base_path']."/uploads/user/big/";
$config['user_img_small_path']                 = $config['base_path']."/uploads/user/small/";
$config['user_big_img_url']			= $config['base_url']."uploads/user/big/";
$config['user_small_img_url']                  = $config['base_url']."uploads/user/small/";
